---

- name: influxdb restart handler
  import_tasks: influxdb.yml
  tags: influxdb


- name: nginx restarthandler
  import_tasks: nginx.yml
  tags: nginx


- name: ssh restart handler
  import_tasks: ssh.yml
  tags: ssh

