- name: Create ssh directory
  file: path=/home/guaka/.ssh state=directory

- name: Copy authorized_keys_NDA-signed
  template: src=../../files/authorized_keys_NDA-signed dest=/home/guaka/.ssh/authorized_keys owner=guaka mode=0600
  tags:
    - ssh
    - authorized_keys

- name: Ensure .ssh owner/rights
  file:
    path: /home/guaka/.ssh/authorized_keys
    owner: guaka
    group: guaka
    mode: 0600
  tags:
    - ssh

- name: Ensure .ssh owner/rights
  file:
    path: /home/guaka/.ssh
    owner: guaka
    group: guaka
    mode: 0700
  tags:
    - ssh
