---

#- name: install and configure enable influxdb
- name: configure enable influxdb
  import_tasks: influxdb.yml
  tags: influxdb


- name: configure and enbale nginx
  import_tasks: nginx.yml
  tags: nginx

## TODO: test if non suplying of version leads to current HEAD?

- name: Clone/pull project repo
  git:
    repo: https://github.com/trustroots/trustroots.git
    dest: /srv/trustroots
    force: yes
    version: "{{ version | default('HEAD') }}"
  tags:
    - git


- name: chown /srv/trustroots guaka
  file:
    dest: /srv/trustroots
    owner: guaka
    group: admin
    mode: u=rwX,g=rX,o=rX
    recurse: yes
  tags:
    - chown
# This should be user trustroots

    
- name: install and configure node
  import_tasks: node.yml
  tags: node


- name: install and configure grafana
  import_tasks: grafana.yml
  tags: grafana

