name: Notify matrix when an issue is created

on:
  issues:
    types: [opened, reopened, transferred]

jobs:
  ping_matrix:
    runs-on: ubuntu-latest
    steps:
      - name: send message for an issue
        uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ secrets.MATRIX_ROOM_ID }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          message: "${{ github.event.issue.user.login }} has just opened an issue: _\"${{ github.event.issue.title }}\"_\n
          ${{ github.event.issue.url }}"
          server: "matrix.org"
